name: Sync LeetCode Submissions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6'  # every Saturday at 8 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: solutions
          verbose: true
          commit-header: "[LeetCode Sync]"
